{
    'name': 'Affiliate Management',
    'old_technical_name': 'to_affiliate_manager',
    'name_vi_VN': 'Cộng tác viên',
    'version': '3.0.2',
    'author': 'T.V.T Marine Automation (aka TVTMA),Viindoo',
    'website': 'https://viindoo.com',
    'live_test_url': "https://v14demo-int.viindoo.com",
    'live_test_url_vi_VN': "https://v14demo-vn.viindoo.com",
    'support': 'apps.support@viindoo.com',
    'summary': 'Manage Affiliates, Affiliate Programs and Commission',
    'summary_vi_VN': 'Quản lý Cộng tác viên, các chương trình cộng tác và hoa hồng Cộng tác viên',
    'sequence': 24,
    'category': 'Sales/Affiliate',
    'description':"""
Product Highlights
==================
Affiliate Management is an Odoo application that extends Odoo's functionality to enable you to run your affiliate program to boost your sales with no effort.

* **Manage Unlimited Affiliates**: No matter how many affiliates you have, the application allows you to manage your affiliate effectively without any pain.
* **Affiliate Program Signup**: Clients can signup your affiliate program within a few clicks. You also can join any of your partners inside your administration panel
* **Automatic Affiliate Code Generation**: Affiliate codes are automatically generated when clients join your affiliate program. On-screen instructions are generated for affiliate quick start.
* **Configurable Cookie Lifetime**: You can define cookie lifetime as long as you want within your configuration panel to meet your business requirements.
* **Configurable Commission Percentage**: You can define your commission base (in percentage against sales order value) for affiliates and change it anytime you want.
* **Minimum Commission Payout**: You can set minimum payout so that an affiliate will not be able to create a payment request if his unpaid commission is less than this amount.
* **Sales Management Integration**: Each quotation/sales order form is added with AffCode field to refer that the order was placed with help of an affiliate. So, you can filter sales orders by this field for better management.
* **Payment & Invoicing Integration**: Seamless integration with Odoo payment & invoicing system. Automatic invoice creation when a commission payment request is approved.

How it works
============
* The application allows clients to sign up and join your affiliate program. Once joined, they will be provided with an affiliate code of seven (7) alphanumeric characters to append into your URL in form of http(s)://yourdomain.com/?affcode=xxxxxxx, where the xxxxxxx is the code generated by the system.
* Then, the newly signup affiliate can put the formed URL to any of web pages where he want to get potential customers. He can also share the URL to his social networks such as Facebook, LinkedIn, etc.
* When a client follows the URL mentioned above to you site, a cookie will be created and store in the client's browser. If the client buys something from your site before the cookie expiry, a commission will be generated and accounted to your the affiliate code owner.
* The affiliate code owner is provided with an affiliate portal so that he can manage their commissions, submit commission payout request, manage paid commission, etc.

Editions Supported
==================
1. Community Edition
2. Enterprise Edition

    """,
    'description_vi_VN':"""
Tính năng
=========
Quản lý Cộng tác viên là một ứng dụng mở rộng tính năng của Odoo để cho phép chạy các chương trình liên kết cộng tác để đẩy mạnh doanh số mà không cần mất quá nhiều công sức.

* **Quản lý các chi nhánh không giới hạn**: Cho dù có bao nhiêu cộng tác viên, ứng dụng cho phép người dùng quản lý cộng tác viên của mình một cách hiệu quả nhất.
* **Đăng ký làm cộng tác**: Khách hàng có thể đăng ký chương trình cộng tác của bạn chỉ bằng vài cú click chuột. Bạn cũng có thể truy cập bảng quản lý cộng tác bất cứ lúc nào.
* **Tự động tạo mã cộng tác**: Mã cộng tác được tạo tự động khi hách hàng đăng ký tham gia chương trình cộng tác của bạn. Hướng dẫn trên màn hình giúp nhanh chóng tạo cộng tác viên.
* **Có thể cấu hình thời gian sử dụng**: Bạn có thể thiết lập vòng đời của cookie trong bảng thiết lập tùy theo mục đích sử dụng.
* **Có thể cấu hình tuổi đời của cookie**: Bạn có thể xác định tuổi của cookie theo mong muốn trong bảng cấu hình để đáp ứng nhu cầu quản lý.
* **Có thể cấu hình tỷ lệ hoa hồng**: Bạn có thể xác định cơ sở hoa hồng của mình (tính theo tỷ lệ phần trăm so với giá trị đơn hàng) cho các đại lý và thay đổi bất cứ lúc nào bạn muốn.
* **Có thể đặt khoản thanh toán hoa hồng tối thiểu**: Bạn có thể đặt khoản thanh toán hoa hồng tối thiểu cho một cộng tác viên. Các cộng tác viên không thể tạo yêu cầu thanh toán nếu số tiền hoa hồng ít hơn mức tối thiểu này.
* **Tích hợp quản lý bán hàng**: Trên form báo giá/đơn hàng bán được thêm trường *Affcode* để gán mã code của đại ký với báo giá/đơn hàng. Vì vậy bạn có thể lọc các đơn hàng theo mã cộng tác để quản lý tốt hơn.
* **Tích hợp hóa đơn và thanh toán**: Tích hợp với hệ thống hóa đơn và thanh toán của Odoo. Tạo hóa đơn tự động khi yêu cầu thanh toán hoa hồng được phê duyệt.

Cách thức hoạt động
===================
* Ứng dụng cho phép khách hàng đăng ký và tham gia làm cộng tác viên. Sau khi tham gia, họ được cung cấp mã cộng tác gồm bảy (7) kí tự chữ và số để thêm vào URL dưới dạng http (s): //yourdomain.com/? Affcode = xxxxxxx, trong đó xxxxxxx là mã do hệ thống tạo ra.
* Sau đó, cộng tác viên ký mới có thể đặt URL mới được tạo vào bất kỳ trang web nào để tìm khách hàng tiềm năng. Cộng tác viên cũng có thể chia sẻ URL lên các mạng xã hội của mình như Facebook, LinkedIn, v.v.
* Khi khách hàng theo URL được chia sẻ đến trang web của bạn, cookie sẽ được tạo và lưu trữ trong trình duyệt của khách hàng. Nếu khách hàng mua một cái gì đó từ trang web của bạn trước khi hết hạn cookie, khoản hoa hồng sẽ được tạo và được tính cho chủ sở hữu mã cộng tác.
* Chủ sở hữu mã cộng tác được cung cấp một cổng thông tin đại lý để có thể quản lý hoa hồng của mình, gửi yêu cầu thanh toán hoa hồng, quản lý hoa hồng dã được thanh toán, v.v.

Phiên bản được hỗ trợ
=====================
1. Community Edition
2. Enterprise Edition

    """,
    'depends': ['account', 'sales_team'],
    'data': [
        'data/sequence_data.xml',
        'data/product_data.xml',
        'security/affiliate_security.xml',
        'security/ir.model.access.csv',
        'views/affiliate_portal_templates.xml',
        'views/affiliate_root_menus.xml',
        'views/affiliate_code_views.xml',
        'views/affiliate_commission_rule_views.xml',
        'views/affiliate_commission_views.xml',
        'views/affiliate_commission_line_views.xml',
        'views/affiliate_payment_views.xml',
        'views/res_config_views.xml',
        'views/account_move_views.xml',
        'views/res_partner_views.xml',
        'views/res_company_form_views.xml',
        'wizard/affiliate_join_view.xml',
        'report/account_invoice_report_view.xml',
        'report/affiliate_report.xml',
    ],
    'images': ['static/description/main_screenshot.png'],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
    'price': 99.9,
    'currency': 'EUR',
    'license': 'OPL-1',
}
