from . import res_partner
from . import res_users
from . import affiliate_code
from . import affiliate_commission_line
from . import affiliate_commission_rule_line
from . import affiliate_commission_rule
from . import affiliate_commission
from . import affiliate_referrer
from . import affiliate_payment
from . import res_config
from . import account_move
from . import account_move_line
from . import res_company
from . import product
